default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>
  pool: 40

development:
  <<: *default
  database: joinville-doa-development

test:
  <<: *default
  database: joinville-doa-test

production:
  <<: *default
  database: joinville-doa-production
  username: app
